fixtures:
    repositories:
        "stdlib":  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        'apache':
          repo: "git://github.com/puppetlabs/puppetlabs-apache.git"
          ref: 0.6.0
        'puppetdb': "git://github.com/puppetlabs/puppetlabs-puppetdb.git"
        'apt': "git://github.com/puppetlabs/puppetlabs-apt"
        'inifile': "git://github.com/cprice-puppet/puppetlabs-inifile.git"
    symlinks:
        "puppet": "#{source_dir}"
