fixtures:
    repositories:
        "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        'concat': "git://github.com/ripienaar/puppet-concat.git"
        'apache': "git://github.com/puppetlabs/puppetlabs-apache.git"
    symlinks:
        "puppet": "#{source_dir}"
