fixtures:
    repositories:
        stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        apache:
          repo: "git://github.com/puppetlabs/puppetlabs-apache.git"
        puppetdb: "git://github.com/puppetlabs/puppetlabs-puppetdb.git"
        inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
        concat: "git://github.com/ripienaar/puppet-concat.git"
        file_concat:
          repo: 'git://github.com/electrical/puppet-lib-file_concat.git'
        apt:
          repo: "git://github.com/puppetlabs/puppetlabs-apt"
          ref: "1.8.0"
    symlinks:
        puppet: "#{source_dir}"
