language: ruby
bundler_args: --without system_tests
rvm:
  - 2.3.1
  - 1.9.3
script: "bundle exec rake test"
env:
  matrix:
    include:
      - rvm: 2.3.1
        env: PUPPET_GEM_VERSION="< 4.0.0"
      - rvm: 2.3.1
        env: PUPPET_GEM_VERSION="< 4.0.0" FUTURE_PARSER="yes" STRICT_VARIABLES="no"
      - rvm: 2.3.1
        env: PUPPET_GEM_VERSION="< 4.0.0" FUTURE_PARSER="yes" STRICT_VARIABLES="yes"
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="> 4.0.0
      - rvm: 1.9.3
        env: PUPPET_GEM_VERSION="> 4.0.0" STRICT_VARIABLES="yes"
