language: ruby
bundler_args: --without system_tests
rvm:
  - 2.3.1
  - 1.9.3
script: "bundle exec rake test"
env:
  - "PUPPET_GEM_VERSION='< 4.0.0' FUTURE_PARSER='yes' STRICT_VARIABLES='no'"
  - "PUPPET_GEM_VERSION='< 4.0.0' FUTURE_PARSER='yes' STRICT_VARIABLES='yes'"
  - "PUPPET_GEM_VERSION='> 4.0.0'"
  - "PUPPET_GEM_VERSION='> 4.0.0' STRICT_VARIABLES='yes'"
matrix:
  exclude:
  - rvm: 2.3.1
    env: "PUPPET_GEM_VERSION='> 4.0.0'"
  - rvm: 2.3.1
    env: "PUPPET_GEM_VERSION='> 4.0.0' STRICT_VARIABLES='yes'"
